kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: {{ .Values.kube_proxy_mode | default "ipvs" }}
  disableDefaultCNI: true
  ipFamily: {{ .Values.ip_family | default "ipv4" }}
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    etcd:
      local:
        dataDir: "/tmp/lib/etcd"

nodes:
{{- range $.Values.workers }}
  - role: control-plane
    image: kindest/node:v1.19.1
{{- end }}
